### ISSUE TITLE
The New Site Release Checklist

### ISSUE THREAD

**Issue by bachmacintosh** [bachmacintosh/new.bachmacintosh.com#8]
ℹ️ We're still building this list out.

# Site-Wide

## Views

- [ ] Finalize new Default View
- [ ] Determine if a Long Content View is still needed; ideally make the Default View suitable for long content

## Tech

- [ ] Decide if we stick with Contentful and Google Sheets, use a new CMS, or combine multiple CMS' (e.g. Git-based for Blog, API based for other things)
- [ ] Rewrite any remaining plain JS pages/components/etc. in TypeScript
- [ ] Restructure Typedefs so they're better organized and not all sitting in `additional.d.ts`

# Site Contents

## Home

- [ ] Rework Home Page to feature more content from new sections

## Blog

- [ ] Improve SEO for Spoiler and NSFW content; make sure search engines can read the post lede when humans can't (until they click through a modal or the like)
- [ ] Move Blog content to new CMS (if it changes)
- [ ] Implement categories and/or tags
- [ ] Implement multiple authors (i.e. multiple people author a single post, a post has a single author besides Collin Bachman, etc.)
- [ ] Update Image Optimization to use `next/future/image`

## Media

(will not be implemented)

## Videos

- [ ] Implement existing Videos page with Videos Featuring Me

## Music

- [ ] Create page(s) for upcoming music catalog organized by Albums, EPs, Singles, and Production Music
- [ ] Albums/EPs/Singles: Provide links to distributed content (e.g. YouTube, Spotify, Apple Music, etc.)
- [ ] Production Music: Provide links to license the tracks, ideally include watermarked previews on site

### GTA Online

- [ ] Implement existing page
- [ ] Add Crates stats to the page

### Other

- [ ] Implement Jackbox Games Selector

### Anime

- [ ] Implement existing page
- [ ] Use daisyUI tooltips instead of Popper
- [ ] Use `next/future/image` 

### WaniKani

- [ ] Rework WaniKani page; organize by Burned Items (past), Study Queue (present), Future Levels (future)
- [ ] Include Locked Items in Future section
- [ ] Decide if we want to keep Recent Unlocks and Critical Condition Items
